
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIG BRACL BRACR CADENA COMILLA CONTENIDO DIFER DIV DOUBLESTRING ENTERO ENTERO FUNCION ID ID IGIG INCR MAS MAY MAYIG MENIG MENO MENOS MULTI NUMB PARA PAREL PARER PUNTOCOMA SEMI SI SINO SIONO STRING VARIABLEinit : program\n                | opcion2\n                | opcion3\n                | opcion4\n                | ububuefunopcion2 : VARIABLE CADENA ID ASSIG ID\n                    | VARIABLE ENTERO ID ASSIG NUMBvar : VARIABLE ENTERO ID ASSIG NUMBopcion3 : opcion2 SI PAREL ID operando contentn PARER BRACL contentIF BRACR SINO BRACL contentELSE BRACRopcion4 : FUNCION ID PAREL ENTERO ID PARER BRACL opcion2 var ID ASSIG ID MAS ID BRACRububuefun : FUNCION ID PAREL CADENA ID PARER BRACL ID ASSIG ID BRACRprogram : PARA PAREL value ID ASSIG NUMB PUNTOCOMA ID operando NUMB PUNTOCOMA ID INCR PUNTOCOMA PARER BRACL content BRACRvalue : CADENA\n                    | ENTEROcontent : CONTENIDO\n                     | IDcontentIF : CONTENIDO\n                     | IDcontentELSE : CONTENIDO\n                     | IDoperando : MAY\n                    | MAYIG\n                    | MENIG\n                    | IGIG\n                    | MENO\n                    | DIFER\n                    | ASSIGcontentn : ID  \n                 | NUMB'
    
_lr_action_items = {'PARA':([0,],[7,]),'VARIABLE':([0,37,38,49,53,],[8,-6,-7,8,60,]),'FUNCION':([0,],[9,]),'$end':([1,2,3,4,5,6,37,38,71,82,86,91,],[0,-1,-2,-3,-4,-5,-6,-7,-11,-9,-10,-12,]),'SI':([3,37,38,],[10,-6,-7,]),'PAREL':([7,10,14,],[11,15,21,]),'CADENA':([8,11,21,],[12,17,27,]),'ENTERO':([8,11,21,60,],[13,18,26,65,]),'ID':([9,12,13,15,16,17,18,24,26,27,28,29,30,31,32,33,34,35,48,50,51,59,61,65,68,69,72,80,81,87,],[14,19,20,22,23,-13,-14,37,39,40,41,-21,-22,-23,-24,-25,-26,-27,52,54,55,64,66,70,73,74,76,84,-8,88,]),'ASSIG':([19,20,22,23,52,54,64,70,],[24,25,35,36,35,61,69,75,]),'MAY':([22,52,],[29,29,]),'MAYIG':([22,52,],[30,30,]),'MENIG':([22,52,],[31,31,]),'IGIG':([22,52,],[32,32,]),'MENO':([22,52,],[33,33,]),'DIFER':([22,52,],[34,34,]),'NUMB':([25,28,29,30,31,32,33,34,35,36,58,75,],[38,43,-21,-22,-23,-24,-25,-26,-27,44,63,81,]),'PARER':([39,40,41,42,43,83,],[45,46,-28,47,-29,85,]),'PUNTOCOMA':([44,63,79,],[48,68,83,]),'BRACL':([45,46,47,67,85,],[49,50,51,72,87,]),'CONTENIDO':([51,72,87,],[57,78,90,]),'BRACR':([55,56,57,66,76,77,78,84,88,89,90,],[-18,62,-17,71,-20,82,-19,86,-16,91,-15,]),'SINO':([62,],[67,]),'INCR':([73,],[79,]),'MAS':([74,],[80,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'init':([0,],[1,]),'program':([0,],[2,]),'opcion2':([0,49,],[3,53,]),'opcion3':([0,],[4,]),'opcion4':([0,],[5,]),'ububuefun':([0,],[6,]),'value':([11,],[16,]),'operando':([22,52,],[28,58,]),'contentn':([28,],[42,]),'contentIF':([51,],[56,]),'var':([53,],[59,]),'contentELSE':([72,],[77,]),'content':([87,],[89,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> init","S'",1,None,None,None),
  ('init -> program','init',1,'p_init','semantico.py',12),
  ('init -> opcion2','init',1,'p_init','semantico.py',13),
  ('init -> opcion3','init',1,'p_init','semantico.py',14),
  ('init -> opcion4','init',1,'p_init','semantico.py',15),
  ('init -> ububuefun','init',1,'p_init','semantico.py',16),
  ('opcion2 -> VARIABLE CADENA ID ASSIG ID','opcion2',5,'p_opcion2','semantico.py',19),
  ('opcion2 -> VARIABLE ENTERO ID ASSIG NUMB','opcion2',5,'p_opcion2','semantico.py',20),
  ('var -> VARIABLE ENTERO ID ASSIG NUMB','var',5,'p_var','semantico.py',35),
  ('opcion3 -> opcion2 SI PAREL ID operando contentn PARER BRACL contentIF BRACR SINO BRACL contentELSE BRACR','opcion3',14,'p_opcion3','semantico.py',44),
  ('opcion4 -> FUNCION ID PAREL ENTERO ID PARER BRACL opcion2 var ID ASSIG ID MAS ID BRACR','opcion4',15,'p_opcion4','semantico.py',89),
  ('ububuefun -> FUNCION ID PAREL CADENA ID PARER BRACL ID ASSIG ID BRACR','ububuefun',11,'p_ububuefun','semantico.py',108),
  ('program -> PARA PAREL value ID ASSIG NUMB PUNTOCOMA ID operando NUMB PUNTOCOMA ID INCR PUNTOCOMA PARER BRACL content BRACR','program',18,'p_program','semantico.py',115),
  ('value -> CADENA','value',1,'p_value','semantico.py',132),
  ('value -> ENTERO','value',1,'p_value','semantico.py',133),
  ('content -> CONTENIDO','content',1,'p_content','semantico.py',138),
  ('content -> ID','content',1,'p_content','semantico.py',139),
  ('contentIF -> CONTENIDO','contentIF',1,'p_contentIF','semantico.py',143),
  ('contentIF -> ID','contentIF',1,'p_contentIF','semantico.py',144),
  ('contentELSE -> CONTENIDO','contentELSE',1,'p_contentELSE','semantico.py',149),
  ('contentELSE -> ID','contentELSE',1,'p_contentELSE','semantico.py',150),
  ('operando -> MAY','operando',1,'p_operando','semantico.py',155),
  ('operando -> MAYIG','operando',1,'p_operando','semantico.py',156),
  ('operando -> MENIG','operando',1,'p_operando','semantico.py',157),
  ('operando -> IGIG','operando',1,'p_operando','semantico.py',158),
  ('operando -> MENO','operando',1,'p_operando','semantico.py',159),
  ('operando -> DIFER','operando',1,'p_operando','semantico.py',160),
  ('operando -> ASSIG','operando',1,'p_operando','semantico.py',161),
  ('contentn -> ID','contentn',1,'p_contentn','semantico.py',166),
  ('contentn -> NUMB','contentn',1,'p_contentn','semantico.py',167),
]
