
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AG AS CM ID IM IN LA LC N NS OP PA PC PQ PT SO TP TP VQ VSS : V\n            | F\n            | CL\n            | IF\n            | Mvalor : N\n                | cadena\n                | IDcadena : CM ID CMV : AG TP ID OP valorF : VQ ID PA P PC LA V C LCIF : V VS PA CD PC LA V C LC NS LA SL LCCD : ID OP ONP : TP IDCL : PQ PA V PT ID OP ON PT ID IN PT PC LA V C LCON : ID\n            | NM : VQ SO PA PC LA V C LCC : IM PA ID PCSL : IM PA cadena PC'
    
_lr_action_items = {'AG':([0,14,36,38,43,71,],[7,7,7,7,7,7,]),'VQ':([0,],[8,]),'PQ':([0,],[9,]),'$end':([1,2,3,4,5,6,29,30,31,32,47,54,58,69,76,],[0,-1,-2,-3,-4,-5,-8,-10,-6,-7,-9,-18,-11,-12,-15,]),'VS':([2,29,30,31,32,47,],[10,-8,-10,-6,-7,-9,]),'TP':([7,17,],[11,24,]),'ID':([8,11,15,22,24,26,28,33,45,55,56,],[12,16,21,29,35,37,39,42,39,59,60,]),'SO':([8,],[13,]),'PA':([9,10,12,13,50,67,],[14,15,17,18,55,70,]),'OP':([16,21,37,],[22,28,45,]),'PC':([18,20,23,35,39,40,41,47,59,65,72,],[25,27,34,-14,-16,-13,-17,-9,62,68,74,]),'PT':([19,29,30,31,32,39,41,47,51,63,],[26,-8,-10,-6,-7,-16,-17,-9,56,65,]),'N':([22,28,45,],[31,41,41,]),'CM':([22,42,70,],[33,47,33,]),'LA':([25,27,34,61,68,],[36,38,43,64,71,]),'IM':([29,30,31,32,44,46,47,48,64,73,],[-8,-10,-6,-7,50,50,-9,50,67,50,]),'LC':([49,52,53,62,66,74,75,],[54,57,58,-19,69,-20,76,]),'NS':([57,],[61,]),'IN':([60,],[63,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,],[1,]),'V':([0,14,36,38,43,71,],[2,19,44,46,48,73,]),'F':([0,],[3,]),'CL':([0,],[4,]),'IF':([0,],[5,]),'M':([0,],[6,]),'CD':([15,],[20,]),'P':([17,],[23,]),'valor':([22,],[30,]),'cadena':([22,70,],[32,72,]),'ON':([28,45,],[40,51,]),'C':([44,46,48,73,],[49,52,53,75,]),'SL':([64,],[66,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> V','S',1,'p_S','analizador.py',72),
  ('S -> F','S',1,'p_S','analizador.py',73),
  ('S -> CL','S',1,'p_S','analizador.py',74),
  ('S -> IF','S',1,'p_S','analizador.py',75),
  ('S -> M','S',1,'p_S','analizador.py',76),
  ('valor -> N','valor',1,'p_valor','analizador.py',79),
  ('valor -> cadena','valor',1,'p_valor','analizador.py',80),
  ('valor -> ID','valor',1,'p_valor','analizador.py',81),
  ('cadena -> CM ID CM','cadena',3,'p_cadena','analizador.py',85),
  ('V -> AG TP ID OP valor','V',5,'p_declaracion_con_asignacion','analizador.py',90),
  ('F -> VQ ID PA P PC LA V C LC','F',9,'p_F','analizador.py',102),
  ('IF -> V VS PA CD PC LA V C LC NS LA SL LC','IF',13,'p_IF','analizador.py',113),
  ('CD -> ID OP ON','CD',3,'p_CD','analizador.py',118),
  ('P -> TP ID','P',2,'p_P','analizador.py',140),
  ('CL -> PQ PA V PT ID OP ON PT ID IN PT PC LA V C LC','CL',16,'p_CL','analizador.py',143),
  ('ON -> ID','ON',1,'p_ON','analizador.py',146),
  ('ON -> N','ON',1,'p_ON','analizador.py',147),
  ('M -> VQ SO PA PC LA V C LC','M',8,'p_SO','analizador.py',150),
  ('C -> IM PA ID PC','C',4,'p_C','analizador.py',153),
  ('SL -> IM PA cadena PC','SL',4,'p_SL','analizador.py',162),
]
